name: Build and Sync WASM to Portfolio

on:
  push:
    branches: [main]

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout connect4
        uses: actions/checkout@v3

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build WASM with Makefile
        run: make wasm

      - name: Clone portfolio repo
        uses: actions/checkout@v3
        with:
          repository: TSSchaef/portfolio
          token: ${{ secrets.PORTFOLIO_PUSH_TOKEN }}
          path: portfolio

      - name: Copy WASM artifacts to portfolio
        run: |
          cp connect4.js connect4.wasm portfolio/public/connect4/
          if [ -f connect4.data ]; then cp connect4.data portfolio/public/connect4/; fi

      - name: Commit and push to portfolio
        run: |
          cd portfolio
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/connect4/connect4.js public/connect4/connect4.wasm
          if [ -f public/connect4/connect4.data ]; then git add public/connect4/connect4.data; fi
          git commit -m "Update connect4 WASM build from connect4@${{ github.sha }}"
          git push
